version: '3.8'

services:
  telegram-bot:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./data:/var/www/html/data
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped